#ifndef __ESP_TRACING_IMPL_H__
#define __ESP_TRACING_IMPL_H__

// utility helper header for libraries integrating with ESP with autotools

#if (defined(HAVE_LIBESP) && HAVE_LIBESP == 1) || (defined(HAVE_ESP) && HAVE_ESP == 1)

#ifdef __cplusplus
#include "esp.h"
#else
#include "esp_c.h"
#endif

#else

#define ESP_DEFAULT_BIN_GENERATOR()
#define ESP_LINEAR_BIN_GENERATOR(size, count, offset)
#define ESP_POW2_BIN_GENERATOR(size_factor, count, offset)
#define ESP_LOG2_BIN_GENERATOR()
#define ESP_DECLARE_SYNC_HISTOGRAM(name, generator, isLatency, isShared, units, factor)
#define ESP_DECLARE_ASYNC_HISTOGRAM(name, generator, isLatency, isShared, units, factor)
#define ESP_DECLARE_ASYNC_HASH_HISTOGRAM(name, generator, isLatency, isShared, units, factor)
#define ESP_SCOPED_LATENCY_HISTOGRAM(name, generator, isShared)
#define ESP_SYNC_HISTOGRAM_SAMPLE(name, generator, isShared, sample)
#define ESP_SYNC_HISTOGRAM_SAMPLE_EX(name, generator, isShared, units, factor, sample)
#define ESP_SYNC_HISTORGRAM_START_TIME(name, generator, isShared, currTime)
#define ESP_SYNC_HISTORGRAM_START(name, generator, isShared)
#define ESP_SYNC_HISTORGRAM_END_TIME(name, generator, isShared, currTime)
#define ESP_SYNC_HISTORGRAM_END(name, generator, isShared)
#define ESP_ASYNC_HISTOGRAM_START_TIME(name, generator, isShared, id, currTime)
#define ESP_ASYNC_HISTOGRAM_START(name, generator, isShared, id)
#define ESP_ASYNC_HISTOGRAM_END_TIME(name, generator, isShared, id, currTime)
#define ESP_ASYNC_HISTOGRAM_END(name, generator, isShared, id)
#define ESP_ASYNC_HISTOGRAM_SAMPLE(name, generator, isLatency, isShared, units, factor, sample)
#define ESP_ASYNC_HASH_HISTOGRAM_START_TIME(name, generator, isShared, id, currTime, collisions)
#define ESP_ASYNC_HASH_HISTOGRAM_START(name, generator, isShared, id, collisions)
#define ESP_ASYNC_HASH_HISTOGRAM_END_TIME(name, generator, isShared, id, currTime, misses)
#define ESP_ASYNC_HASH_HISTOGRAM_END(name, generator, isShared, id, misses)
#define ESP_DECLARE_SYNC_SNAPSHOT_TIMER(name)
#define ESP_DECLARE_ASYNC_SNAPSHOT_TIMER(name)
#define ESP_DECLARE_ACCUMULATING_TIMER(name)
#define ESP_DECLARE_GLOBAL_ACCUMULATING_TIMER(name)
#define ESP_SCOPED_SNAPSHOT_TIMER(name)
#define ESP_SCOPED_ACCUMULATING_TIMER(name)
#define ESP_SYNC_SNAPSHOT_TIMER_START_TIME(name, currTime)
#define ESP_SYNC_SNAPSHOT_TIMER_START(name)
#define ESP_SYNC_ACCUMULATING_TIMER_START_TIME(name, currTime)
#define ESP_SYNC_ACCUMULATING_TIMER_START(name)
#define ESP_SYNC_SNAPSHOT_TIMER_END_TIME(name, currTime)
#define ESP_SYNC_SNAPSHOT_TIMER_END(name)
#define ESP_SYNC_ACCUMULATING_TIMER_END_TIME(name, currTime)
#define ESP_SYNC_ACCUMULATING_TIMER_END(name)
#define ESP_SYNC_SNAPSHOT_TIMER_END_CONTEXT(name, context)
#define ESP_SYNC_ACCUMULATING_TIMER_END_CONTEXT(name, context)
#define ESP_ASYNC_SNAPSHOT_TIMER_START_TIME(name, id, currTime)
#define ESP_ASYNC_SNAPSHOT_TIMER_START(name, id)
#define ESP_ASYNC_ACCUMULATING_TIMER_START_TIME(name, id, currTime)
#define ESP_ASYNC_ACCUMULATING_TIMER_START(name, id)
#define ESP_ASYNC_SNAPSHOT_TIMER_END_TIME(name, id, currTime)
#define ESP_ASYNC_SNAPSHOT_TIMER_END(name, id)
#define ESP_ASYNC_ACCUMULATING_TIMER_END_TIME(name, id, currTime)
#define ESP_ASYNC_ACCUMULATING_TIMER_END(name, id)
#define ESP_ASYNC_ACCUMULATING_TIMER_REF(name, refName, refTimerScope, sampleType)
#define ESP_ASYNC_SNAPSHOT_TIMER_START_CONTEXT(name, id, context)
#define ESP_ASYNC_ACCUMULATING_TIMER_START_CONTEXT(name, id, context)
#define ESP_ASYNC_SNAPSHOT_TIMER_END_CONTEXT(name, id, context)
#define ESP_ASYNC_ACCUMULATING_TIMER_END_CONTEXT(name, id, context)
#define ESP_DECLARE_LEVEL_COUNTER(name, type, units, factor)
#define ESP_REPORT_COUNTER_LEVEL_TIME(name, level, currTime)
#define ESP_REPORT_COUNTER_LEVEL(name, level)
#define ESP_REPORT_COUNTER_INC_TIME(name, increase, currTime)
#define ESP_REPORT_COUNTER_INC(name, increase)
#define ESP_REPORT_COUNTER_DEC_TIME(name, decrease, currTime)
#define ESP_REPORT_COUNTER_DEC(name, decrease)
#define ESP_GET_COUNTER_LEVEL(name, level)
#define ESP_SCHEDULE_REPORT_COUNTER_LEVEL(name, readFunc)
#define ESP_SCHEDULE_REPORT_COUNTER_LEVEL_EX(name, sampleRateMicros, readFunc)
#define ESP_SCHEDULE_REPORT_COUNTER_LEVEL_FILE(name, filePath)
#define ESP_SCHEDULE_REPORT_COUNTER_LEVEL_FILE_EX(name, filePath, sampleRateMicros)
#define ESP_CANCEL_REPORT_COUNTER_LEVEL(name)
#define ESP_REPORT_STAT_VAR(name, value)
#define ESP_DECLARE_RATE_VAR(name, units, factor)
#define ESP_REPORT_RATE_VAR_LEVEL_TIME(name, level, currTime)
#define ESP_REPORT_RATE_VAR_LEVEL(name, level)
#define ESP_REPORT_RATE_VAR_INC_TIME(name, increase, currTime)
#define ESP_REPORT_RATE_VAR_INC(name, increase)
#define ESP_GET_RATE_VAR_VALUE(name, value)
#define ESP_GET_RATE_VAR_RATE(name, rate)
#define ESP_SCHEDULE_REPORT_RATE_VAR(name, readFunc)
#define ESP_SCHEDULE_REPORT_RATE_VAR_EX(name, sampleRateMicros, readFunc)
#define ESP_SCHEDULE_REPORT_RATE_VAR_FILE(name, filePath)
#define ESP_SCHEDULE_REPORT_RATE_VAR_FILE_EX(name, filePath, sampleRateMicros)
#define ESP_CANCEL_REPORT_RATE_VAR(name)
#define ESP_DECLARE_BW_METER(name)
#define ESP_REPORT_BW_METER_TIME(name, currTime, value)
#define ESP_REPORT_BW_METER(name, value)
#define ESP_DECLARE_BUSY_METER(name, timeLimitNS)
#define ESP_REPORT_BUSY_METER_START_TIME(name, currTime)
#define ESP_REPORT_BUSY_METER_START(name)
#define ESP_REPORT_BUSY_METER_START_TIME_EX(name, timeLimitNS, currTime)
#define ESP_REPORT_BUSY_METER_START_EX(name, timeLimitNS)
#define ESP_REPORT_BUSY_METER_END_TIME(name, currTime)
#define ESP_REPORT_BUSY_METER_END(name)
#define ESP_REPORT_BUSY_METER_END_TIME_EX(name, timeLimitNS, currTime)
#define ESP_REPORT_BUSY_METER_END_EX(name, timeLimitNS)
#define ESP_SCOPED_BUSY_METER(name)
#define ESP_TRACE_CONTEXT(name, id, context)
#define ESP_TRACE(name, id)
#define ESP_TRACE_DISPATCH_HISTOGRAM(traceName, histogram, sampleType)
#define ESP_TRACE_DISPATCH_TIMER(traceName, timer, sampleType)
#define ESP_TRACE_DISPATCH_SCOPED_TIMER(traceStartName, traceEndName, timer)
#define ESP_TRACE_DISPATCH_LEVEL_COUNTER(traceName, levelCounter, contextParser)
#define ESP_TRACE_DISPATCH_RATE_VAR(traceName, rateVar, contextParser)
#define ESP_TRACE_DISPATCH_STAT_VAR(traceName, statVar, contextParser)
#define ESP_TRACE_DISPATCH_BUSY_METER(traceName, busyMeter, sampleType)
#define ESP_CUE(name, scope)
#define ESP_CLUSTER_CUE(name)
#define ESP_NODE_CUE(name)
#define ESP_RANK_CUE(name)
#define ESP_THREAD_CUE(name)
#define ESP_BEGIN_CUE(name, scope)
#define ESP_CUE_REF()
#define ESP_END_CUE()
#define ESP_CUE_ADD_INT_PROP(propName, propVal)
#define ESP_CUE_ADD_STR_PROP(propName, propVal)
#define ESP_CUE_ADD_BOOL_PROP(propName, propVal)
#define ESP_CUE_ADD_FLOAT_PROP(propName, propVal)
#define ESP_CUE_ADD_NAME_ID_PROP(propName, propVal)
#define ESP_PUSH_CUE(name)
#define ESP_BEGIN_PUSH_CUE_EX(name)
#define ESP_END_PUSH_CUE_EX()
#define ESP_POP_CUE(name)
#define ESP_SCHEDULE_CUE(name, scope, periodMicros)
#define ESP_SCHEDULE_CUE_EX(name, scope, periodMicros, propHandlerFunc)
#define ESP_SCHEDULE_RANK_CUE(name, periodMicros)
#define ESP_BEGIN_BATCH_REPORT()
#define ESP_CURR_TICK_COUNT
#define ESP_END_BATCH_REPORT()

#endif // HAVE_LIBESP == 1

#endif // __ESP_TRACING_IMPL_H__
